#!/usr/bin/env python3
"""Rebuild the run index from run artifacts.

Every generation run already records its own policy version and configuration,
but that provenance is spread across one ``run_config.json`` per tag, so tracing
"what did version N change and what did it score" means opening dozens of files.
This regenerates a single sorted index from those artifacts.

    PYTHONPATH=generalized_card python3 generalized_card/scripts/build_version_log.py

It only reads artifacts; the narrative notes live in ``VERSION_LOG.md`` and are
never overwritten.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
RUNS_ROOT = REPO_ROOT / "artifacts/generalized_card/runs"
DEFAULT_OUTPUT = REPO_ROOT / "generalized_card/RUN_INDEX.md"

METRICS = (
    "self_bleu_4",
    "self_bertscore_mean_f1",
    "semantic_mean_cosine",
    "hard_disagree_rate",
    "polite_rate",
    "impolite_rate",
    "neutral_rate",
    "length_cv",
    "avg_depth",
    "structural_virality",
    "mean_story_probability",
    "emotion_entropy",
)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--runs-root", default=str(RUNS_ROOT))
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    rows = [
        row
        for run_dir in sorted(Path(args.runs_root).iterdir())
        if run_dir.is_dir()
        for row in (_row(run_dir),)
        if row
    ]
    rows.sort(key=lambda row: (row["version"], row["tag"]))

    lines = [
        "# Generalized CARD Run Index",
        "",
        "Generated by `generalized_card/scripts/build_version_log.py`. Do not edit",
        "by hand; rationale for each version belongs in `VERSION_LOG.md`.",
        "",
        "`pass` counts metrics with both MWU and KS p-values above 0.05.",
        "A blank result column means the run was never evaluated.",
        "",
        "A pass count is only comparable against another run with the same",
        "`coverage` (generated comments / matched real comments). Truncated threads",
        "have fewer comment pairs, which lowers the pairwise diversity metrics and",
        "inflates the pass count. See VERSION_LOG.md.",
        "",
        "| version | tag | threads | comments | coverage | policy | pass |",
        "|---:|---|---:|---:|---:|---|---:|",
    ]
    for row in rows:
        coverage = f"{row['coverage']:.2f}" if row["coverage"] else ""
        lines.append(
            f"| {row['version'] or ''} | `{row['tag']}` | {row['threads']} | "
            f"{row['comments']} | {coverage} | {row['policy']} | {row['passes']} |"
        )
    lines.append("")
    lines.append("## Per-metric MWU p-values for evaluated runs")
    lines.append("")
    lines.append("| tag | " + " | ".join(m[:14] for m in METRICS) + " |")
    lines.append("|---|" + "---:|" * len(METRICS))
    for row in rows:
        if not row["metrics"]:
            continue
        cells = []
        for metric in METRICS:
            value = row["metrics"].get(metric)
            if not value:
                cells.append("-")
                continue
            mwu = value.get("mwu_p_value")
            ks = value.get("ks_p_value")
            mark = "*" if (mwu or 0) > 0.05 and (ks or 0) > 0.05 else ""
            cells.append(f"{mwu:.3f}{mark}" if mwu is not None else "-")
        lines.append(f"| `{row['tag']}` | " + " | ".join(cells) + " |")
    lines.append("")

    output = Path(args.output)
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {output} ({len(rows)} runs)")


def _row(run_dir: Path) -> dict[str, Any] | None:
    config = _load(run_dir / "run_config.json")
    if not config:
        return None
    policy = str(
        config.get("generator_policy_version")
        or config.get("card_core_policy_version")
        or ""
    )
    threads, comments = _generated_size(run_dir)
    coverage = _structural_coverage(run_dir, comments)
    metrics = _load(run_dir / "matched_evaluation/matched_seed_group_eval.json")
    passes = ""
    if metrics:
        passes = str(
            sum(
                1
                for metric in METRICS
                if (metrics.get(metric) or {}).get("mwu_p_value", 0) > 0.05
                and (metrics.get(metric) or {}).get("ks_p_value", 0) > 0.05
            )
        )
    return {
        "tag": run_dir.name,
        "policy": policy or "(unrecorded)",
        "version": _version_number(policy),
        "threads": threads,
        "comments": comments,
        "coverage": coverage,
        "passes": passes,
        "metrics": metrics,
    }


def _structural_coverage(run_dir: Path, comments: int) -> float:
    """Return generated comments over the matched real comments for these seeds.

    Every pairwise diversity metric is a mean over comment pairs, so a run that
    omits structural slots is measured on a smaller thread than the one it is
    compared against and scores better for the wrong reason. Reporting coverage
    beside the pass count is what makes two runs comparable.
    """

    seed_pool = _seed_comment_counts(run_dir)
    if not seed_pool:
        return 0.0
    seeds: set[int] = set()
    for path in run_dir.glob("generated/run_*/generation_records.json"):
        for record in _load_list(path):
            index = record.get("seed_index")
            if isinstance(index, int) and index >= 0:
                seeds.add(index)
    matched = sum(seed_pool.get(index, 0) for index in seeds)
    return comments / matched if matched else 0.0


def _seed_comment_counts(run_dir: Path) -> dict[int, int]:
    config = _load(run_dir / "run_config.json")
    path = str(config.get("seed_post_pool_json") or config.get("seed_pool") or "")
    if not path:
        return {}
    payload = _load(Path(path))
    counts: dict[int, int] = {}
    for row in payload.get("seed_posts") or []:
        try:
            counts[int(row["seed_index"])] = int(row["real_num_comments"])
        except (KeyError, TypeError, ValueError):
            continue
    return counts


def _load_list(path: Path) -> list[Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    return payload if isinstance(payload, list) else []


def _version_number(policy: str) -> int:
    """Return the generation version, not the ``generalized-card-v2`` family tag.

    Every policy string starts with the profile family, so the generation
    version is the last ``-vNN-`` component rather than the first.
    """

    matches = re.findall(r"-v(\d+)-", policy)
    return int(matches[-1]) if matches else 0


def _generated_size(run_dir: Path) -> tuple[int, int]:
    threads = comments = 0
    for path in sorted(run_dir.glob("generated/run_*/discussion.json")):
        payload = _load(path)
        for post in payload.get("posts") or []:
            threads += 1
            stack = list(post.get("comments") or [])
            while stack:
                comment = stack.pop()
                comments += 1
                stack.extend(comment.get("replies") or [])
    return threads, comments


def _load(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


if __name__ == "__main__":
    main()
